# Generated by Django 5.2.7 on 2025-10-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='side2',
            new_name='back',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='side1',
            new_name='front',
        ),
    ]
